<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CSV_Panel</name>
   <tag></tag>
   <elementGuidId>ad15e88a-e6d0-428b-a5fc-7175fed5c99c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[contains(@class, 'ui-menu')]/li/a[text()='CSV']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-6 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d323e3a-9199-47da-b77a-d1562e1be538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/download/jqueryui/menu/menu.csv</value>
      <webElementGuid>abd471d3-dfb5-4c6a-b274-eaf0584b59cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSV</value>
      <webElementGuid>683b386e-6529-4ddd-846b-6cbffb0dedc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-6&quot;)/a[1]</value>
      <webElementGuid>11f91200-d885-4516-adf1-7fbbb61072e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ui-id-6']/a</value>
      <webElementGuid>0ab1cb26-e0f2-40b6-8a48-185afcf48844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CSV')]</value>
      <webElementGuid>91d0ad1e-9009-405f-8d8c-819454a1123b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[1]/following::a[1]</value>
      <webElementGuid>4ea424e4-fe13-4604-8c5a-19fd477f8532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JQuery UI Menus'])[1]/following::a[6]</value>
      <webElementGuid>66ab26f9-198e-44f9-bf61-815ff112f956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excel'])[1]/preceding::a[1]</value>
      <webElementGuid>5cb9e425-d4cb-4720-b411-a2e4ab8b04bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to JQuery UI'])[1]/preceding::a[2]</value>
      <webElementGuid>d36843ba-f709-4901-84db-f051b063b66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CSV']/parent::*</value>
      <webElementGuid>0265f033-3752-4ac2-a548-00c7cfcbd1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/download/jqueryui/menu/menu.csv')]</value>
      <webElementGuid>646d6610-e817-4a93-9ee1-6d67bc928d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/ul/li[2]/a</value>
      <webElementGuid>ca54d496-dd59-43c9-a33d-8fc74db2f806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/download/jqueryui/menu/menu.csv' and (text() = 'CSV' or . = 'CSV')]</value>
      <webElementGuid>3594c7eb-d1aa-42a0-92f0-80aeda12fe52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
