<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Drag_and_Drop_Panel</name>
   <tag></tag>
   <elementGuidId>da6e725b-a314-4b39-8563-df7e888c7a9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='/drag_and_drop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(10) > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/drag_and_drop' and (text() = 'Drag and Drop' or . = 'Drag and Drop')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54c14d68-dab7-4394-b26c-83bde84abe68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/drag_and_drop</value>
      <webElementGuid>89f05b00-af13-463f-9b30-a880499cca9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag and Drop</value>
      <webElementGuid>87182c86-1175-48a4-86be-888425196379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[1]/li[10]/a[1]</value>
      <webElementGuid>3dd51663-b368-44c6-a25f-4494c20d1ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li[10]/a</value>
      <webElementGuid>3534d56c-7903-4c86-a840-5b587ef39f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Drag and Drop')]</value>
      <webElementGuid>9780b185-8ef6-45fb-936b-46cc75d8dc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disappearing Elements'])[1]/following::a[1]</value>
      <webElementGuid>9d61748f-07f9-4660-b8bb-00bca35af80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digest Authentication'])[1]/following::a[2]</value>
      <webElementGuid>ea131068-71c8-48d2-9423-e8aad8691db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown'])[1]/preceding::a[1]</value>
      <webElementGuid>c5c6a3de-401c-4add-ae87-184452311419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Content'])[1]/preceding::a[2]</value>
      <webElementGuid>e26bd697-c520-4253-b211-418ee971f388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drag and Drop']/parent::*</value>
      <webElementGuid>658fff06-0a68-45f6-9be2-66abe7499a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/drag_and_drop')]</value>
      <webElementGuid>4e5e678b-32c5-4211-b65d-3272a35ab1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>371c8523-e516-415c-a126-cee06081a46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/drag_and_drop' and (text() = 'Drag and Drop' or . = 'Drag and Drop')]</value>
      <webElementGuid>f704c65c-5218-4d62-bec3-0c0d63bb8d62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
