<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sortable_Data_Tables_Panel</name>
   <tag></tag>
   <elementGuidId>522dfca0-1843-4ac7-b8b8-e06848438630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/ul/li[41]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(41) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>afbd9775-4f1c-4310-a838-9e755d6c2a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tables</value>
      <webElementGuid>3861b322-6528-4cac-a234-f5a1d354ddd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sortable Data Tables</value>
      <webElementGuid>2af00207-2218-4093-8e03-1446f6476733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[1]/li[41]/a[1]</value>
      <webElementGuid>91d44665-f1bf-48a6-a1b3-3ba0ce6924a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li[41]/a</value>
      <webElementGuid>7e247000-da07-43d6-a155-7dda46e6c895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sortable Data Tables')]</value>
      <webElementGuid>04a39faa-cda8-447a-9efa-f2788305f1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slow Resources'])[1]/following::a[1]</value>
      <webElementGuid>9deb7bac-7314-47a9-a4bc-bf81de462ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shifting Content'])[1]/following::a[2]</value>
      <webElementGuid>a8b03c1a-27aa-4ab6-adc8-35c70b8a8968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Codes'])[1]/preceding::a[1]</value>
      <webElementGuid>08b796b2-0874-49a0-84f0-8dc9a99b7a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typos'])[1]/preceding::a[2]</value>
      <webElementGuid>932ea96e-af82-44a3-ac59-fddd5e89c3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sortable Data Tables']/parent::*</value>
      <webElementGuid>ef372c5c-755c-4846-9518-819b4f37e4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tables')]</value>
      <webElementGuid>3c61a3cf-e163-4716-8266-92122557c7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[41]/a</value>
      <webElementGuid>6a2ae0e6-0d4f-4988-86e5-ffc885ff7fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tables' and (text() = 'Sortable Data Tables' or . = 'Sortable Data Tables')]</value>
      <webElementGuid>e75b911e-a854-4ae2-95ce-94a5b1d1e89c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
