<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Username_TextBox</name>
   <tag></tag>
   <elementGuidId>939bf991-3f96-432a-bd2d-e99c70036c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>ebbc58b5-3fa6-4139-b71c-662d0a7d9e3f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
