<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>G_Label</name>
   <tag></tag>
   <elementGuidId>0750195e-f6d7-418b-a24a-00d7c4bc7851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#result</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='result']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3c15aa72-0b0f-484c-b518-06877d975ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>result</value>
      <webElementGuid>df589ecf-23b9-4431-8144-ddd0a2d59a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You entered: G</value>
      <webElementGuid>5eef1d58-a361-4ade-a931-c49ab5b917a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)</value>
      <webElementGuid>487bf67f-4a2f-4913-97bd-b5ba11d1d2a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='result']</value>
      <webElementGuid>8402cb8f-5d0c-424f-bcee-97126e62ad0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/p[2]</value>
      <webElementGuid>4ebaecd2-eb7a-4253-a514-d084d9b65e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Key Presses'])[1]/following::p[2]</value>
      <webElementGuid>0b851e53-b163-424f-8694-06cf351ea9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elemental Selenium'])[1]/preceding::p[1]</value>
      <webElementGuid>11003016-0683-46d1-83c6-c9ff19301c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You entered: G']/parent::*</value>
      <webElementGuid>3b9c0ba1-b4d3-403e-8389-de5752604fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>d8a3e2ca-413f-4728-8bcd-2a4b0b581841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'result' and (text() = 'You entered: G' or . = 'You entered: G')]</value>
      <webElementGuid>bc88cc99-37a3-4cad-83d8-e009c8d5c9c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
