<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Key_Presses_Panel</name>
   <tag></tag>
   <elementGuidId>0258a0c1-5f5d-446c-90a2-0c90ac4fb2a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(31) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='/key_presses']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d4c3721-f9ad-4279-8fb2-05167c4d55a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/key_presses</value>
      <webElementGuid>daa8d0b5-bf51-4f02-b005-def45ba0db15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Key Presses</value>
      <webElementGuid>87e55aa3-9969-4cf7-abe9-e9ace742dd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[1]/li[31]/a[1]</value>
      <webElementGuid>ef737a7a-d1cb-4fc2-bb5d-c9b2df4bb1ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li[31]/a</value>
      <webElementGuid>331d0cde-c264-485c-bf23-f8324a471329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Key Presses')]</value>
      <webElementGuid>a1a1f0a1-f1e2-4e02-98aa-211051ddfac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript onload event error'])[1]/following::a[1]</value>
      <webElementGuid>160e5c28-a5a8-47d2-9320-f6e88f8da549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript Alerts'])[1]/following::a[2]</value>
      <webElementGuid>da3824fc-548d-486a-b3f8-383627332599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Large &amp; Deep DOM'])[1]/preceding::a[1]</value>
      <webElementGuid>8089ea51-a7aa-4c02-bcf9-2e9daea04716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multiple Windows'])[1]/preceding::a[2]</value>
      <webElementGuid>c2f657f9-de0e-49f3-9804-0b84a7e50e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Key Presses']/parent::*</value>
      <webElementGuid>ac2d7662-8dee-4e44-bfba-c5498b8efbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/key_presses')]</value>
      <webElementGuid>339cec9b-4468-4832-856b-a05489500498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[31]/a</value>
      <webElementGuid>acbd14a1-9c30-43be-af6d-41d48bffdea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/key_presses' and (text() = 'Key Presses' or . = 'Key Presses')]</value>
      <webElementGuid>b1e6346d-25f5-4b9b-b4ac-5590e3c5ad17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
